### ISSUE TITLE
Badly formatted table in the JP documentation

### ISSUE THREAD

**Issue by yoshimis** [IgniteUI/igniteui-angular-api-i18n#25] opened 2018-12-19 07:55 UTC
https://jp.infragistics.com/products/ignite-ui-angular/docs/sass/#function-igx-drop-down-theme
![image](https://user-images.githubusercontent.com/9547754/50206483-e7395d80-03ae-11e9-9628-dc48d47bddde.png)

**Comment by valadzhov** [comment] 2018-12-19 10:38
Assigning this to Alex as I'm not seeing any differences between the EN and JP json files. There aren't any missing nodes between the two and the JP json is being validated, it's not missing or has any unnecessary characters which might cause this formatting issue.

**Comment by Aleksandyr** [comment] 2018-12-19 13:06
@yoshimis @valadjov This again is not a bug into the plugins but incorrectly structured comments.
So again I'm going to log this [issue ](https://github.com/IgniteUI/igniteui-angular/issues/3484)into [igniteui-angular](https://github.com/IgniteUI/igniteui-angular) repository.

**Closed** 2018-12-19 13:06 UTC
Labels: bug, sassdoc
